sudo: required

language: generic

services:
  - docker

branches:
  only:
    - master
    - staging
    - prod

cache:
  directories:
    - ~/bundle-cache
    - ~/coverage-cache

stages:
  - Build
  - name: Test
    if: type = pull_request # This is designed to cut out unnecessary runs of the test suite. See PSD-821 for details.
  - name: Update code coverage
    if: branch = master AND type = cron
  - name: Run regression tests
    if: branch = master AND type = cron
  - name: Deploy to int
    if: branch = master AND type = push
  - name: Deploy to staging
    if: branch = staging AND type = push
  - name: Deploy to production
    if: branch = prod AND type = push

jobs:
  include:
    - stage: Build
      before_install:
        - mkdir -p ~/bundle-cache
        - mkdir -p ~/coverage-cache/cosmetics
        - mkdir -p ~/coverage-cache/psd
      install:
        - BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} ./infrastructure/ci/build-docker-images.sh

    - stage: Test
      name: PSD Tests
      script: COMPONENT=psd-web ./infrastructure/ci/test-if-changed.sh
      env: &test_env
        - COVERALLS_PARALLEL=true
    - name: PSD Static Analysis
      script: COMPONENT=psd-web ./infrastructure/ci/static-analysis-if-changed.sh

    - stage: Deploy to int
      name: Deploy PSD web
      script: COMPONENT=psd-web ./infrastructure/ci/travis-wait.sh ./infrastructure/ci/deploy-if-changed.sh
      env: &deploy_int_env
        - SPACE=int
        - BRANCH=${TRAVIS_BRANCH}
        - BUILD_ID=${TRAVIS_BUILD_NUMBER}
        - CF_STAGING_TIMEOUT=30 # Extend CF staging timeout to 30 minutes
        - secure: qoP7Gbk7CpO6BXtgw4XfopbWMjO0ssO70BsK8sgDtA5vi2z7Bw+vPyjeAVg9vVzjbLl8TP0Bee+yterHZ7sZ5CEaZ+3QSFz+CO9QFoKFXW9E8TZC4NuNJoRun28MueNOJEF3PmT4rSJUlgfL1yrshezrjD5W5Ol9aTG70my0yZnJeyESfKAxFEypPAi9SetzZVvtX8co3I1ZKRoHfb9UHh5KhShl5RLbFQjBI77maCyI4w7GWP8gKPGX7423hIj5H2qvYGRyUYb6/NLQW51V0ra+yK21nBgNmqrzp9uV83iSpoMsRKU2sDV3hbux/YWmvzrvA1xgGf/YkJkXUMz3QAnps6nVrtTj5yF/7/m2xkLJXjZgpZ/343ou2gxJjiXg9+4TohTSIs9bqJV3nZPiodJKMOcuGUuzlxozSwtwmSp7iOkoDWZpDrAq4BdyEbUnl/Ys6vrwloahPYssamphXqVY3LC6pv3akNFsQpU/+Fq1aWoRVn2p6vTQ62TmqZcWNsYYIGeqn8zlIL+x2i5V1wwtfafLtQWFSearvXPOt/ZtinpaM1eV1ojb2ITopxJw7MEm1C3T9Psvw7jw1lZKAY76OqJTGzqvM5hYaIq7YeGGfg/PeA/+n5MFZj28dp/3FulHLS38ei76XIyNodh0UtK59JZ+b9ZopMPg4oQ/0Rc= # CF_USERNAME
        - secure: "pUsN/mgQ2I4QRu6fy26psKByDedBS1fzlHPFo7mLjjhuQjFo60LxOUw2HvXr9/AahK4Z4Pbfcw23IqRCwiXef/hIBR1Jml/x7f4/vSTve1iqUGv29dv/e7HSt6q33IwbaFZCthD5ameg8TEGb4GBN0nElKEJ1Fy9aU/99AK1aL452XLFy7bcsTaktbOrZlwx2XH82kYKAWiSf1GrHtpiAsQ/OT3AOczvDPeILRfXVZ2VTp1JcIkZNscZG6NhcJW5qDq1bknaPnQZ9gONr1J+zxN4gA+Z7iy31LAoYudngachyJ9jprgmjfKOw25zCJdPCkf02xlzCAoxpV8RDdTab089043BkVdxmDCocMsXdDJm9QCOGUP16w0D5yXoOEUG7oGW4MWJTow1qyBmC86phpUNyUUBabcLlQ7hUdiGw5rUaww8B9eUj6dboiYpeisETpGDdeSAchEZtx7Cx7al7twZtGgxYFUQehU+fE48wx+SHn3VoKIduWC8oB1yg+nc94MluCisjPe5u74D6ymQHYwd3G5kIFB1T61MA8HPmIplYK8RQ1FSd9QcbcMuToZbRsTgZ3Uf33Y+bO85lSZ1C+0bGxDdx4LkcvfFHGbADO10p6PpFrQRqg2Xpa+sVfCK3MXo+/EpWxH2prTMSrELaHnUmG2YVAES/EMc9YfOSJM=" # CF_PASSWORD
        - secure: AtLt0OhSuL4tO3T22c4efJrXMrAeZN36Wc2xC0PYlwFQrjOOLcPOxZoLQ5+23ViuEKq5ZpCUbnIVkvS5qsFwDW5R5aARBjbPfeO32GG9/cekvbwF6egKSD9F4liRlGlFIlo/pVb7Xvgy+CM2iLUc2EwteRFbaNCSq34uhu8Sposg94cJDaj4upLBI7hH0N6GPtcjvA+ZOdQaOe8/AJ6+D7TuoeJnOSgDzgQTtgtsnDl+feXpzzEoA+jruvQpGBIo3U3PjX31h98qqR3BFTjFzgjNlBly6H/RJkZrh0DAq0Sky3uqrsVVOZcPVRrUwHZl8QR8H8BHQvpLXiLEM+uyhZgnPRNsBddvTIVzFT0e4qYPITMhuGNAEgWVuD7fAh3yc8hPFALSuJod4h5Kp0leg+EJOra620iD/B2GT5yevGRAjBhCbSI3AgnEHvcFtYNV1CQ8372pUa7Yhhz513NzGYNreIJx8/Sfdt7jkD/B/AuMZP+lpu7cFITRU1Z/WMp053opN3bEhEBO0TXZCu9XMYk2sbYoi8SwgnA6YQxXmy+SH04zxzRSzB+gaIISJSJjbZ0LqGH0zHje/3TbkSZYcw0aQvnklA14iSNK4e/ExlrBGCnQjv45xu0OvVEHQkX/T5EN0/8WVeDHOLcGOPZLNRWozqQuFEaBopfH3gBC8Fk= # PSD_BASIC_AUTH_USERNAME
        - secure: UY2cncCCvyyzEzlEuELifMiYaxBg67TuFwR9ClLN7DqH6nxTKNBjyeDNpqYokU7PPfzWnsfrV/P28a5QRKiIVp4R4nZKPP1kQ36I64y3FiVxDdkCOa/znzkuoyL9BI0vxIALHgqoD02/tuEuW3SqoQZtpyvFs8+nq/iWNWp/4/ewkaCCzwR6A6X3/Svz4iLoF4g0cQdp5hha+wVJYUTOGLjqNhPz6ND07GemnlXpTQ7HtfcvsvXwo3LNFBWF4z6HZIcXl8vbVNQl5KTu0QyHojaBbZSYH5IkPJRZ1SnoNFESVB3t10IQKr9X8SB9BPXsQKyXA5PZlW/gK1x8FR7mg04shmJ6Mthe/0Mvu2IToIsMrbV7s/LpmpU2aboy9Mkr9ZlvCZ4qzWLypLVdykVxEdIWeDgB9q13t9xUGiM8116HZD4p8NhbiBp9vBKjxmRbhKhQHRl97jeB0DQqIWSlL8Ckv/UtlxtCvdpWKLEsRgFIjUYFhdIb0YN+fODdu1BzXPdZUKA/cEEkPJ1+ztgWpmxVT/ebsaoOQ1OFLwCiBIyAwCx1POtBllNvpS78ygKavDnbp6EEx3sjw5mHpvu4a/SbOmqageQvJzuh7xoWrvRZ8IYMERP3fUdnUb3jRaecFBIYDV13sPsk/pFuYW0PJ1+6b7HT/5jie6qCuMLdViw= # PSD_BASIC_AUTH_PASSWORD
    - name: Deploy PSD worker
      script: COMPONENT=psd-worker ./infrastructure/ci/deploy-if-changed.sh
      env: *deploy_int_env

    - stage: Deploy to staging
      name: Deploy PSD web
      script: COMPONENT=psd-web ./infrastructure/ci/travis-wait.sh ./infrastructure/ci/deploy-if-changed.sh
      env: &deploy_staging_env
        - SPACE=staging
        - BRANCH=${TRAVIS_BRANCH}
        - BUILD_ID=${TRAVIS_BUILD_NUMBER}
        - CF_STAGING_TIMEOUT=30 # Extend CF staging timeout to 30 minutes
        - secure: oVIrfF2Kuqc764xtW7+KxbQRRR1OpuHg0t34DFUqwe/mpy6flHq8F6R0V9u3hlS5VzgWu36UYVq2atL0gzNs+ekzXyGpjCiEtDyIjdZIfyj9EADYaRwHpM/rNJ/HQHB5qx44RtCE7JSGV28EPkSbbYrwVhklud7Nkp9lDPno4GweAk2e0EYUXsUUyC638wX/u6eWiXKEk3nZhQKyPYfWMBbhsfjmft/nzkrEAtphJnNXPaPDR/vtRQlgXdMLaM/twY9wNK+Mih8dfc1UpSjRICIi4NGIX5Tu9Lh2r4HkaBJWL2KXn6Lxt/Q2LcpwimQ+/HEjuifp3YaCkXo6tIWtYny6kUwo3xWcg03IuhMJ87xbk8nxP6GCp1Qf4qYr2NI8hSNJPeKQlht5kRxkrhUoMHgSqv1CgITeUaY5s5mSE18ykQzgV9Zygs8crQv5komA5wQ1h00k/cvutjk0579tcBzivwAuzqaYrHaYNtqE7trYQ6fk1x4of2VrhS96CtPhlwFzvB+UyUNE+a9OZm223nVxbEWeUnJuVYnqag4Qt03maVh6LFCcbPrcmnFRLWwBMpdlS4xEjCNYRKwNCAvGMrp7918HZnOVFKZqUUP3lvIZJQehMEPJzMwmoDeq9Zn9P4fTk4N4ubuyQs2iVYTjxXdDHPoe9zd6in5gHQM8Uss= # CF_USERNAME
        - secure: "xakLUBW+GLK+Lj5JT51iCa8PPmx6s0aZGlPKHovrbcAZHXbejhRiQiuK6KUv6VC1+ozQtaJOsboTwMz2rY63YMtzZ79wB8I4ZO21+NDfmkk6JTYxAy6+4CilyPgu6EGczRh7VoJ+zcvDBkN/egm0dNvfEyX/5SXtnbgIew1lxkbPYMD1TF5YCV7wUFVDBCIWKG7WMlgqHTUIBQ9FtUpFNq9b55nD61/FqJi/q7dCb//NDoopcQp636t6nJ6OO6vbIPA34jYK2IUjlhpyqaNPFG1agOOQxt738nwxqWvi+zJevGsgU0T26j76+GQxCWz4LAkdjZ4H6DhchasUTGkgdH4f5xSS44BpNChXyaMvaA9E9WewZO2epSQIV3TxWAlNv6cwBnf3O64yiVXd5iPA140nQyF3Q6BSAjQokuBn4dCf1o87wsWPz3t8ehQmtOnJAyvW4SvwluQOVjjT5Cc7nFQpKiy9piizp+J77fGV/X8Y+LwjIeSWoY2fyRY0eWDY6d6jPomSeLWQG1ZNDIC0g5KTBA69o8PB5xNdenXcUb3qnmHKoC7OQ2rurCsf6HDTCUT/5Q4Go984cWkwV8kf8pRDDTNxsD5BuYdULbDoezYwnKB14VlKbTdAhV150NzHR8v8SYWueLQoZFwmMsN8Baxe3ch8xVNudMLcCxkP9To=" # CF_PASSWORD
        - secure: fMxdrVkJwKQrlszdq5lRMvUrmkYuHEJwIcmA8cWh8TeLak5m7t+EQgbEX/4DjpOclKWtd0/p80JaO36aVpkkMoTgQ/JW3q9vWpGaP2w4uLSfd6A+32ltgQCtpyO0dAeUXE1X5eY10oBwAsKydMZtMecE1dFPkBtcbY0U0no744Pf4yMOOa/V4iiD3RBB/ZRDSSGou2bkLdXDzgbjDLuugP4qmmnuS2IMzsrJpFtqh8aDGZd2vtCRiS3niKCshIUN/9/YX60lQi3b9BU1ZIS4Wz8LrYXPBhJBbRgZOYJ4qBoq0lUNdPkGKbtWt2qDGs6tJJ/LKqjLcAAa1ONgdhwy+q+C+5+fg1jHD8bN7hPcp+Smh5cuAg8oznHf+XdV9ZO+R3XudvGyehJxyNGRGAyJLbOlaK0eERQVDruNRFXoqerrnaI6v1LV4IZ1JQTdptGqDEegGIXk0sddgImovkVAkFwcNSq7crU/NbnCbCvy3kDXrd7nRIzso08V9I5Tcj13K2CjVhJE9Z1VNIZCx3ScUmnqS+1QvuJzJZEup2i7Z55CzXBxWJD9thIIden/4wvfiW6DpO+kEIbWMx30Jviri1jdfs+GtvUhapYw1oHEbMV9hwNRh+JjbI6T18UDwE3qHlDNqSjI/AWPt7oaMlMdySjkcoYRu2SHkKpivkFIeho= # PSD_BASIC_AUTH_USERNAME
        - secure: fCxsuNP1V7vOTBd5qUUApHYFz9Tt5YbS0j4DeaqWITx+l2axK9dS2hRVOw50ozNH7z1HOINfh6HeT5jhC+QkCsfSfUUQW6anQ5Edk+7qOHQrEXw6yd4EeotRU1WZT9cRyYFHDDoBru0wY97oMdZwnUg9uZt7+ESQbhywPS/dZzjG1ldnoaZ0VwJ6GUZQQG1xdYwVuXgpCuNgcjrDit2Qa+TUJtnYiee5F+tmit5ZLlKhrRaCfKvPVDtv+J+KtYD2MyXwlgf6Xntp/5miEIg2gjyeaCK1LrTXjHgChyit5NzFu2lfY0VQFZX+H2c8RAH12Oqx2Bvri5cZJj8X+Q+sSJnsK5YuJjbP1He3rsqsvZsl/XWHBNp/PCCPNpQtWrClN4H0AlorboNhLkGpohZwC1/o/m6+GkvvFcLJ1WkSkjBMjyP0RCRjMQ2oZdfickAlisTTHRr6WUM6IXmx8AiEK5iLx9P47/ODNrUuh9BiJ6NMf3bhzsi1rsrz/d8Ycvwa/Hq8jL7Sz349iNvpil64VV9MQ9Earwjgp+Ned2dbpvhdwnAWm1HnZH7MyT/LoQBZntVWaegXJ7AKkA66/CMyhBRgBnwyLssh/TFhtL0q2LqAQ2zrhxj4OT+u5TrzewDi6kKhMTYmGr+paztVF/T7b6PTMhry1c1bDy8oX5bOIks= # PSD_BASIC_AUTH_PASSWORD
    - name: Deploy PSD worker
      script: COMPONENT=psd-worker ./infrastructure/ci/deploy-if-changed.sh
      env: *deploy_staging_env

    - stage: Deploy to production
      name: Deploy PSD web
      script: COMPONENT=psd-web ./infrastructure/ci/travis-wait.sh ./infrastructure/ci/deploy-if-changed.sh
      env: &deploy_prod_env
        - SPACE=prod
        - BRANCH=${TRAVIS_BRANCH}
        - BUILD_ID=${TRAVIS_BUILD_NUMBER}
        - CF_STAGING_TIMEOUT=30 # Extend CF staging timeout to 30 minutes
        - secure: fXT1dyOFJiElJ1dLvPICDKhHFypSTa0+soCxxOuAcAMJK049h69GvkxDU9CKj471ZQwFs2PUYnGBu0r/J2hgAKDVIIN3ch3kJP7sEbi0ye8WXteIojIAelrcCuueKazhCORRPlJVOojXCMwtLpAyRi4qAev563jM+4CeivcY3W9xEmbZCMPuSsp/2cp5yVIQ0c/B4TgMG5T8tLLvPdUIHcHkxQURMJnFh10zVpSsUBwlCrVxAFNPLcaxVQyQ0xFEivw4HsYVrvfQ6Rh3i31PWAzupzb11ZolqQ1W43Z2jXCFAUjBZ48vMzsIsSMcws1kaPkN07R3Gtwuxurzp96AI68NoA+lf8xbzeCHsFkDO/rfmmVgXwi3nObXHUMInIazO4ZRwoHHoofl4YsmxPpYfkm1gtq15uh5/d8Xl7CWe7fU5xl0CPutpAOaPnoTcTzhMwaDyRVWzm0t4wzcBR2psKBi9c3kaRTFpz2K8K7xIuQ3ke2Smf+l6cZj0cgcb5OpdT79qLshgZPw3svsV8iS2akeq22Qg2qSPe2Mu8hhjAx0V1+nlnMuTeSOEa9s93QQR8jX2E4uqkWNo8zshKeCbMp591TnW8Hkzjzoi2m0sRDYZuRBbuIG0N2NqCnWspGamijGa8/zUbbFL1Cax9RmzIh24Hn6G1MyCa729ssdHZ0= # CF_USERNAME
        - secure: "KjiTT1SGQAZO9SGJfXRDMYJF0o2bmJgzQLtZQ6paflRmNOvso3RSItMPJDj8Y/OP8tAmNtpq32QJIzw2Gk5XG8z/K1WfTdnEg6dWQg2AOzgbn4xDqG4JYt02Qv1SEMkjo2WepUtgWQZjAtqfgzyWm9iKhe/u6rY1xPDk/Zz4KvI9u8vcAsoGDDS9B1i7CQ+8ncoC43ZS6vg6PgjDFHyEv0EymXC0rZEnRpOwInPqF/lW11vPMPljhg3WXZpzykX4qaD3SR6y8D57MO3YYDJqULPuOWji3abuyTxLIhA8uHIekgRDT2hhM83FPwDXoGk9pCz0gxvahOJiTECftgoyAy+3zdzecz973rsZKP29UIfGSRtIz6s6Tt5duG6xXUgReK9N9MH3Uf77nbB4u/NgwaU0WyEBpR8LEaNBHaUoPLivGw8aeWtQAt7NYbLi+S3pifuIFZtZ1od6ImAdcaejva3la+7Cew7Zb+9hCqJQTaGvB7fCTYoWLY/loR/d/DQS6FleE6C+0RvrRzg/pjrVlML1V8len4Gi2XFMHrLGSgJBGoPaMyw264lg8Ul4O3L1e5AlnRUehNuae7UIUmKey51OWsWNUZmW4KEJqIceNqiYprn/D4U06TnTLlDZesL2fPDIUZh2THiUS2fTcEin7ebnvB1qZ8kSGITReCIBINs=" # CF_PASSWORD
    - name: Deploy PSD worker
      script: COMPONENT=psd-worker ./infrastructure/ci/deploy-if-changed.sh
      env: *deploy_prod_env

    - stage: Update code coverage
      name: PSD coverage
      script: COMPONENT=psd-web ./infrastructure/ci/update-code-coverage.sh
      env: COVERALLS_PARALLEL=true

notifications:
  webhooks: https://coveralls.io/webhook

env:
  global:
    - secure: "eUzvg4G/8AK9wKLhsULy8OsP+x7LMADp+r/W+uWyTVyTKJVo1/PFW1oW/Es/UQ34qHziGv6n5KZhKkJ0cV5SMGWBo8jYnorecCMSA3wR8WNpw6IkAlz3FcWSW1vHVq1FFAz/TwXzE361nqToEgMaNSw8jDW4wRRZpe4R5tUku8kMNo/I1uAFyuiDi5o5kIHFC77Jpeq9gf9luPVMXQCZlqPzqfumueDIRorJBSh6Rnjf6T5HhOBisga/56wswK+lU9mwiRoyfPAxXmie7wnHtM5NRPGOdSZ5FgJj5NpjW7NRD0ciIxBZbj1BwU7skHzVc5gB98hDe5FVWEarxzlVsSw4TzsFkIrz1g61Y4LMWQgpPJl/o9sa5rxm+057/e53i2bVJvG0Nlzw+MhWZUXX5pWWgAl2JkPqmhyVSt6qBgpNwOlKfZyQnZ2R8wA0zoU2dIUBygqCe0YtnPEy6P5lZ4E+WWtsSmbxcoLZgF6o/XhQ9d/kLu4MF0i9sg69FXNF44RfDFXWimzkJlJ+Heho8AJhz6z3vPoXAIUvOIDTwKkE8aF2OxoCo7z37feL4iMlszACk1/qIqdEHocpurtBlH0gbD8ysXfhH+ONtthl1zayKoqThVUFSAzhP1tIPbacTVVWT+xhEP3tMM5fD/rnjDZr6hjBvbiGhNDFeqFF9Lc=" # DOCKER_USERNAME
    - secure: "LZn8cTgUxksukiRbClwcGXiK/QPfFZHIymF2bb02naZoC8zl0bYKdOjt7acvM9/fa8KRTTV1NybxoKXRBUKjeR3lk11vFYPCvaFYx9PZYjMpvG/gMIHF3Z2JcdmKWJK2JoX//FhwcnOWIFvmJKVEsJAyLLm1KU7HKbrEZgMdywzOLAvX7CHTrVRF0zQnJNRRkwIqIfqcEGMG8XzSlgwnhvXRgCg8qVY4ebonKN1S+mHUrtlmZ/1E845D05+1WdiopK/GwAPJl1+6h58Mi2dozefRatqnz/D9uhCB48y4RKf3cs1WbPf+x465fA2QfBSrbdHTG0uk7xKcL1qS9t7SCzujU8w//D+PhfovgQ10k7vurwwcIMnaxTp80FUTR4fHYZWZBKj7Z6w3W7WeqNoSpS8g5a2ypOPt+UmaFjzS74C2ZbCEEXgsnr6zjPVFnCDdWeVxYYs1t8czqDnJ8N84Qqd69/qOpDMaOD+I9qxEEzfEGePV+4/7FhTGAAvBsTapl83H26rjenRoxnLHCTFI7ERxsHM/FPERJQVGPT/Jn1XEFV06FTfLbE0m/XcH2IO3HgL8CnEv5aKaNSl6j6tvQjD7FGlZ6TOj2LgLLLwTxMha5/R9KZdNofS++t9kqHmRl83yiP04345Ih6Dp8JPyLQXouUQ9PLpwZFIVzU6DBh0=" # DOCKER_PASSWORD
    - secure: f3S6q8IhKr8KXOZccuwpBmOna35iTUUSfMUc4YPrhNmaqfi87f7nX3Fn3rCR2Jwckve0rIOghXqfovLT1Z3lrGyyOBePYIR+5YOoF/uUiD3MHCBhm+YxekNENQZzegEG/cgsH15NciAOHyl5YWfuaboONHoy1NmAGQnylrIz81ujWpHNbyRqexVr0KzIPZo/NFaagjnp4Xzn1MvmWp5ESSI+9Y3m1aXSlIQXECcGH/arHYu4JmfnnmeSjpjbgxoYG7eQszBhWFOS0T8PmxlfB1J6O8xyUeYcfPeXzKaVLnFgfegDr3buHD7gRP0phz/49mmv58HSxxfH6Vr6xDUU3W8z1yoOeaYxi697HMnEz0JTHQmGzs5syYVoi98I1qAvZzg3Fu1lcMM5POVOgv31Z82pal0cngqihRXXqxZXwq052Dx1PSWeQNlrcGPv5HFtbCwt/e0h4aFg1UIpRjSXVQ4Qu+v6+LoLU8qF4S1PLKKxW1n355f6K22OxEgpP58bbfsGX6y1oFrrVhvXOHBEKLBw8Kn/jwaRig6CuGWie22YyaEmx32m8N9Roc7sj1cnBK5dQK+VpO8qOg9fCUTfe8acFtvVwhPraAwiAKaKPRyVH4qUQ/6/cO71F2wSjk6FWEwofWU8IrJ8o274n5O1BUWP26pEQSiBS+7X8HAuu4E= # NOTIFY_API_KEY
