version: '3'

services:
  db:
    image: postgres:10.5
    volumes:
      -  ${PWD-.}/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - KEYCLOAK_DATABASE=keycloak
      - KEYCLOAK_DATABASE_HOSTNAME=db
      - KEYCLOAK_DATABASE_USERNAME=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=password

  keycloak:
    image: keycloak:latest
    environment:
      - KEYCLOAK_DATABASE=keycloak
      - KEYCLOAK_DATABASE_HOSTNAME=db
      - KEYCLOAK_DATABASE_USERNAME=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=password
      - NOTIFY_API_KEY=FUNKY_KEY
      - NOTIFY_SMS_TEMPLATE_ID=8b758d39-29ad-4f02-bb52-a68cfac007b6
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "9990:9990"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data

  redis:
    image: redis
    hostname: redis

  psd-web:
    build:
      context: .
      dockerfile: ./psd-web/Dockerfile
    volumes:
      # ${PWD-.} calls PWD on systems which have that variable, and . on others e.g. windows
      - ${PWD-.}/psd-web:/psd-web
      - ${PWD-.}/shared-web:/psd-web/vendor/shared-web
      - bundle-cache:/usr/local/bundle
    environment:
      - DATABASE_URL= postgres://postgres@db
    depends_on:
      - db
      - keycloak
      - elasticsearch
      - redis
      - psd-worker

  psd-worker:
    build:
      context: .
      dockerfile: ./psd-worker/Dockerfile
    command: bin/sidekiq -C config/sidekiq.yml
    volumes:
      # ${PWD-.} calls PWD on systems which have that variable, and . on others e.g. windows
      - ${PWD-.}/psd-web:/psd-web
      - ${PWD-.}/shared-web:/psd-web/vendor/shared-web
      - bundle-cache:/usr/local/bundle
    depends_on:
      - db
      - elasticsearch
      - redis

volumes:
  postgres-volume:
  elasticsearch-volume:
  bundle-cache:
