default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", 'db') %>
  username: <%= ENV.fetch("DATABASE_USERNAME", 'postgres') %>
  password:
  pool: 5

development:
  <<: *default
  database: psd_development

test:
  <<: *default
  database: psd_test

production:
  url: <%= ENV["VCAP_SERVICES"] && CF::App::Credentials.find_by_service_name("psd-database")["uri"] %>
  connect_timeout: 2
  variables:
    statement_timeout: <%= ENV["STATEMENT_TIMEOUT"] || "500ms" %>
